import { TopBar } from "@/components/panel/TopBar";
import { Card } from "@/components/panel/Card";
import { prisma } from "@/lib/prisma";

const ROLE_LABEL: Record<string, string> = {
  OWNER: "Owner",
  CLINIC_MANAGER: "Clinic Manager",
  FRONT_DESK: "Front Desk",
  ESTHETICIAN: "Esteticista",
};

function monthRange() {
  const now = new Date();
  const start = new Date(now.getFullYear(), now.getMonth(), 1);
  const end = new Date(now.getFullYear(), now.getMonth() + 1, 1);
  return { start, end };
}

function monthLabel() {
  return new Date().toLocaleDateString("es-MX", { month: "short", year: "numeric" });
}

// Equipo → Comisiones. Per-staff/per-period totals (spec §5.4) plus a
// detail-per-transaction breakdown and the attribution-override log — all
// real CommissionEntry rows now, generated by createSaleAction at checkout
// (same-day tag match → tagging esthetician; otherwise whoever closed the
// sale). Admin-visible only in Fase 1 — staff self-service "My Commission"
// is Phase 2 per the signed rescope.
export default async function AdminCommissions() {
  const { start, end } = monthRange();
  const entries = await prisma.commissionEntry.findMany({
    where: { createdAt: { gte: start, lt: end } },
    include: {
      user: true,
      saleLineItem: { include: { sale: { include: { client: true } }, product: true, protocol: true } },
      overriddenFrom: true,
    },
    orderBy: { createdAt: "desc" },
  });

  const byUser = new Map<
    string,
    { staff: string; role: string; service: number; retail: number; total: number }
  >();
  for (const e of entries) {
    const row = byUser.get(e.userId) ?? {
      staff: e.user.name,
      role: ROLE_LABEL[e.user.role] ?? e.user.role,
      service: 0,
      retail: 0,
      total: 0,
    };
    if (e.basis === "SERVICE" || e.basis === "ADD_ON") row.service += e.commissionMxn;
    if (e.basis === "RETAIL") row.retail += e.commissionMxn;
    row.total += e.commissionMxn;
    byUser.set(e.userId, row);
  }
  const perPerson = [...byUser.values()].sort((a, b) => b.total - a.total);

  const overrides = entries.filter((e) => e.isOverride);

  return (
    <>
      <TopBar title="Comisiones" allowBothLocations />
      <div className="flex-1 space-y-6 px-4 py-6 min-[860px]:px-8">
        <Card title={`${monthLabel()} — por persona`}>
          {perPerson.length === 0 ? (
            <p className="py-6 text-center font-body text-sm text-ciruela/50">
              Sin comisiones generadas este mes todavía.
            </p>
          ) : (
          <table className="w-full font-body text-sm text-ciruela">
            <thead>
              <tr className="text-left text-xs uppercase tracking-wide text-ciruela/40">
                <th className="pb-2">Personal</th>
                <th className="pb-2">Rol</th>
                <th className="pb-2 text-right">Servicio</th>
                <th className="pb-2 text-right">Retail</th>
                <th className="pb-2 text-right">Total</th>
              </tr>
            </thead>
            <tbody>
              {perPerson.map((c) => (
                <tr key={c.staff} className="border-t border-ciruela/8">
                  <td className="py-3">{c.staff}</td>
                  <td className="py-3 text-ciruela/60">{c.role}</td>
                  <td className="py-3 text-right text-ciruela/60">${c.service.toLocaleString()}</td>
                  <td className="py-3 text-right text-ciruela/60">${c.retail.toLocaleString()}</td>
                  <td className="py-3 text-right font-medium">${c.total.toLocaleString()} MXN</td>
                </tr>
              ))}
            </tbody>
          </table>
          )}
        </Card>

        <Card title="Detalle por transacción">
          {entries.length === 0 ? (
            <p className="py-6 text-center font-body text-sm text-ciruela/50">Sin transacciones este mes.</p>
          ) : (
          <table className="w-full font-body text-sm text-ciruela">
            <thead>
              <tr className="text-left text-xs uppercase tracking-wide text-ciruela/40">
                <th className="pb-2">Fecha</th>
                <th className="pb-2">Personal</th>
                <th className="pb-2">Clienta</th>
                <th className="pb-2">Concepto</th>
                <th className="pb-2 text-right">Base</th>
                <th className="pb-2 text-right">Tasa</th>
                <th className="pb-2 text-right">Comisión</th>
              </tr>
            </thead>
            <tbody>
              {entries.map((t) => (
                <tr key={t.id} className="border-t border-ciruela/8">
                  <td className="py-2.5 text-ciruela/50">{t.createdAt.toISOString().slice(0, 10)}</td>
                  <td className="py-2.5">{t.user.name}</td>
                  <td className="py-2.5 text-ciruela/60">{t.saleLineItem?.sale.client?.name ?? "Mostrador"}</td>
                  <td className="py-2.5 text-ciruela/60">
                    {t.saleLineItem?.product?.name ?? t.saleLineItem?.protocol?.name ?? t.basis}
                  </td>
                  <td className="py-2.5 text-right text-ciruela/60">${t.baseAmountMxn.toLocaleString()}</td>
                  <td className="py-2.5 text-right text-ciruela/50">{t.ratePct ?? "—"}%</td>
                  <td className="py-2.5 text-right font-medium">${t.commissionMxn.toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
          )}
        </Card>

        <Card title="Registro de atribución — anulaciones manuales">
          <p className="mb-4 font-body text-xs text-ciruela/50">
            Regla por defecto: la esteticista que etiquetó la recomendación se lleva la
            comisión si la clienta compra el producto el mismo día; si no, se la lleva quien
            cerró la venta. Toda anulación manual queda registrada aquí.
          </p>
          {overrides.length === 0 ? (
            <p className="py-4 text-center font-body text-sm text-ciruela/50">
              Sin reasignaciones manuales este mes.
            </p>
          ) : (
          <ul className="divide-y divide-ciruela/8">
            {overrides.map((a) => (
              <li key={a.id} className="py-3 font-body text-sm">
                <p className="text-ciruela">
                  {a.saleLineItem?.product?.name ?? "Línea de venta"} —{" "}
                  {a.saleLineItem?.sale.client?.name ?? "Mostrador"}
                </p>
                <p className="mt-1 text-xs text-ciruela/50">
                  Por defecto: {a.overriddenFrom?.name ?? "—"} → Asignado a:{" "}
                  <span className="text-ciruela">{a.user.name}</span> ·{" "}
                  {a.createdAt.toISOString().slice(0, 10)}
                </p>
                <p className="mt-1 text-xs italic text-ciruela/50">&ldquo;{a.overrideReason}&rdquo;</p>
              </li>
            ))}
          </ul>
          )}
        </Card>
      </div>
    </>
  );
}
